#
# ==== General info ====
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared.
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance.
#
debug: false

# A <percentage> of Endermans attack players immediately on spawn and ignore carved pumpkins
nasty-enderman:
  percentage: 0.1

# Arrow archers have a chance to add both <positive> and <negative> effects to their arrows
nasty-archer:
  positive-percentage: 0.3
  negative-percentage: 1.0

# Shooting mobs target the closest player immediately when spawned with direct vision to them
angry-shooter:
  percentage: 100

# The Ender Dragon has <increased regen>, explosion <resistance> and <damage limit>,
# <periodically resurrects> healing crystals,
# and targets <fireballs> and random endermans to aggressive players.
nasty-ender-dragon:
  enabled: true
  world-name: world_the_end
  resurrection-interval-in-s: 30
  # According to https://minecraft.fandom.com/wiki/Ender_Dragon,
  # the Ender Dragon has 200.0 health.
  explosion-damage-limit-per-s: 50.0
  explosion-damage-reduction: 5.0
  balls-interval-in-s: 3
  regen-multiplier: 2.0

# A <percentage> of shooters equip explosive projectiles
explosive-shooter:
  percentage: 1.0
  power: 2.0

# Villagers don't sell imbalanced clothes with <environmental protection> and <mending>
greedy-villager:
  replace-protection: true
  replace-mending: true