#
# ==== General info ====
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared.
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance.
#
debug: false

# A <percentage> of Endermans attack players immediately on spawn and ignore carved pumpkins
nasty-enderman:
  # <float:0..100>
  # The value was set based on feedback from a server with 14 active players,
  # up to 11 online, with both hardcore and casual profiles.
  percentage: 0.033
  # <boolean>
  info-log-about-actions: true
  # <string>
  baby-world-pattern: "world.*"
  # <integer:0..1_000_000>
  baby-distance-to-center: 3_000
  # <float:0..100>
  baby-percentage: 33.3

# Arrow archers have a chance to add both <positive> and <negative> effects to their arrows
nasty-archer:
  # <float:0..100>
  positive-percentage: 0.3
  # <float:0..100>
  negative-percentage: 1.0

# Shooting mobs target the closest visible player immediately when spawned, and then occasionally
angry-shooter:
  # <float:0..100>
  # 0 to disable all targeting
  percentage: 100
  # <integer:0..300>
  # 0 to disable occasional checks
  try-angering-interval-in-s: 30
  # <integer:1..3600_000>
  #
  # Show a warning when periodic player tracking takes more time than expected.
  #
  # When reporting to the plugin Author with details about
  # the players online, other plugins, previous log records, etc.,
  # you may request an improvement of the plugin for your server.
  timeout-in-ms: 5

# The Ender Dragon has <increased regen>, explosion <resistance> and <damage limit>,
# <periodically resurrects> <resurrection-amount> healing crystals,
# and targets <fireballs> and random endermans to aggressive players.
nasty-ender-dragon:
  # <boolean>
  enabled: true
  # <string>
  world-name: world_the_end
  # <integer:0..300>
  resurrection-interval-in-s: 30
  # <integer:0..10>
  resurrection-amount: 2
  # According to https://minecraft.fandom.com/wiki/Ender_Dragon,
  # the Ender Dragon has 200.0 health.
  # <float:0..200>
  explosion-damage-limit-per-s: 50.0
  # <float:0..200>
  explosion-damage-reduction: 5.0
  # <integer:0..300>
  balls-interval-in-s: 3
  # <float:0..200>
  regen-multiplier: 2.0

# A <percentage> of shooters equip explosive projectiles
explosive-shooter:
  # <float:0..100>
  percentage: 1.0
  # <float:0..16>
  power: 2.0

# Villagers don't sell imbalanced clothes with <environmental protection> and overprice imbalanced <mending>
greedy-villager:
  # <boolean>
  replace-protection: true
  # <boolean>
  overprice-mending: true
  # Disabling all flags above, you'll disable the whole section
  # <boolean>
  info-log-about-actions: true

# Players flying too high are frozen
limit-elytras:
  # <boolean>
  enabled: true
  # <integer:-10_000..10_000>
  initial-height-excess: 10
  # <integer:1..300>
  # According to https://minecraft.wiki/w/Powder_Snow#Freezing,
  # after seven seconds, the player begins taking damage
  # so the player start taking damage at 10 + 3 * 7 = 31 height excess.
  height-per-freeze-second: 3

# A <percentage> of Spiders multiply <amount> times on death into smaller <scale> and faster <speed>
hydra-spiders:
  # <float:0..100>
  percentage: 5.0
  # <integer:0..10>
  amount: 3
  # <float:0..2>
  scale: 0.7
  # <float:0..2>
  speed: 1.3
  # <float:0..2>
  health: 0.7
  # <boolean>
  info-log-about-actions: true

# A <percentage> of Phantoms explode with <power> and <cooldown> when give damage, take damage, or die
radical-phantoms:
  # <float:0..100>
  percentage: 33.3
  # <float:0..16>
  power: 3.0
  # <integer:1..300>
  cooldown: 5
  # <boolean>
  info-log-about-actions: true
